# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
  ARTIFACT_DIRECTORY: lib
  BUILT_LIB_LOCATION: dist/godeltech/project-analyzer-cli/lib
  COVERAGE_LOCATION: coverage
  LIB_LOCATION: projects/godeltech/project-analyzer-cli
  LIB_SRC_LOCATION: projects/godeltech/project-analyzer-cli/src
  PACKAGE_NAME: '@godeltech/project-analyzer-cli'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: 'Build'
  variables:
    versionSuffix: ''
    currentPackageVersion: ''
  jobs:
    - job: Lib
      displayName: 'Build and test lib'
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '18.x'
          displayName: 'Install Node.js'
        - script:
            npm install # npm run build to be added
          displayName: 'npm install'

        - task: Npm@1
          displayName: 'Linting'
          inputs:
            command: 'custom'
            customCommand: 'run lint'

        - task: Npm@1
          displayName: 'Unit tests'
          inputs:
            command: 'custom'
            customCommand: 'run test:ci'

        - task: Npm@1
          displayName: 'Security audit'
          inputs:
            command: 'custom'
            customCommand: 'audit'

        - task: Bash@3
          displayName: 'Set version suffix'
          condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
          inputs:
            targetType: 'inline'
            script: |
              echo "##vso[task.setvariable variable=versionSuffix]-ci-$BUILD_BUILDNUMBER"

        - task: PowerShell@2
          displayName: 'Get current version'
          inputs:
            targetType: 'inline'
            workingDirectory: '$(System.DefaultWorkingDirectory)/$(LIB_LOCATION)'
            script: |
              npm version | ConvertFrom-Json | Select-Object -ExpandProperty $(PACKAGE_NAME) | Set-Variable -Name packageVersion
              Write-Host "##vso[task.setvariable variable=currentPackageVersion;]$packageVersion"

        - task: PowerShell@2
          displayName: 'Update version'
          condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
          inputs:
            targetType: 'inline'
            workingDirectory: '$(System.DefaultWorkingDirectory)/$(LIB_LOCATION)'
            script: |
              npm --no-git-tag-version version $(currentPackageVersion)$(versionSuffix)

        - task: Npm@1
          displayName: 'Build'
          inputs:
            command: 'custom'
            customCommand: 'run build'

        - task: PublishPipelineArtifact@1
          displayName: 'Publish Pipeline Artifac in $(ARTIFACT_DIRECTORY) directory'
          inputs:
            path: '$(System.DefaultWorkingDirectory)/$(BUILT_LIB_LOCATION)'
            artifact: '$(ARTIFACT_DIRECTORY)'

        - task: PublishCodeCoverageResults@2
          displayName: 'Publish code coverage result'
          condition: succeededOrFailed()
          inputs:
            summaryFileLocation: '$(COVERAGE_LOCATION)/cobertura-coverage.xml'
            failIfCoverageEmpty: true

        - task: PublishTestResults@2
          displayName: 'Publish test result'
          condition: succeededOrFailed()
          inputs:
            testResultsFormat: JUnit
            testResultsFiles: "**/junit.xml"

- stage: Artifacts
  displayName: 'Artifacts'
  dependsOn: Build
  jobs:
    - deployment: Publish
      displayName: 'Publish lib in artifacts'
      environment: 'Artifacts'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: Npm@1
                displayName: 'Publish lib in artifacts'
                inputs:
                  command: 'publish'
                  workingDir: '$(Pipeline.Workspace)/$(ARTIFACT_DIRECTORY)'
                  publishRegistry: 'useFeed'
                  publishFeed: '19324bbd-9baf-4407-b86d-3e7f0d145399/19b42d8e-fc7a-4ddc-bbb6-f4a97000f284'

- stage: Npm
  displayName: 'Npm'
  dependsOn: Artifacts
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
    - deployment: Publish
      displayName: 'Publish lib in npm registry'
      environment: 'npm'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: Npm@1
                displayName: 'Publish lib in npm registry'
                inputs:
                  command: 'publish'
                  workingDir: '$(Pipeline.Workspace)/$(ARTIFACT_DIRECTORY)'
                  publishEndpoint: 'npm'
